// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loginService.proto

package org.baeldung.grpc;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.baeldung.grpc.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messageResponse = 1;</code>
   */
  java.lang.String getMessageResponse();
  /**
   * <code>string messageResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageResponseBytes();
}
