// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loginService.proto

package org.baeldung.grpc;

public final class LoginServiceOuterClass {
  private LoginServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_baeldung_grpc_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_baeldung_grpc_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_baeldung_grpc_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_baeldung_grpc_LoginResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022loginService.proto\022\021org.baeldung.grpc\"" +
      ".\n\014LoginRequest\022\014\n\004user\030\001 \001(\t\022\020\n\010passwor" +
      "d\030\002 \001(\t\"(\n\rLoginResponse\022\027\n\017messageRespo" +
      "nse\030\001 \001(\t2Z\n\014LoginService\022J\n\005login\022\037.org" +
      ".baeldung.grpc.LoginRequest\032 .org.baeldu" +
      "ng.grpc.LoginResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_baeldung_grpc_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_baeldung_grpc_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_baeldung_grpc_LoginRequest_descriptor,
        new java.lang.String[] { "User", "Password", });
    internal_static_org_baeldung_grpc_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_baeldung_grpc_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_baeldung_grpc_LoginResponse_descriptor,
        new java.lang.String[] { "MessageResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
