// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loginService.proto

package org.baeldung.grpc;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.baeldung.grpc.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user = 1;</code>
   */
  java.lang.String getUser();
  /**
   * <code>string user = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string myRole = 3;</code>
   */
  java.lang.String getMyRole();
  /**
   * <code>string myRole = 3;</code>
   */
  com.google.protobuf.ByteString
      getMyRoleBytes();
}
